defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

gpu_idx: "cpu"
seed: 42
nEpochs: 100

# where to store results
outputpath: "/home/user/results/"
experimentname: "default"

# validation and save intervals
validation_every_N_sampels: 5000
special_save_nEpoch: [100,200]

trainroutine:
  _target_: "train.EuroSat" # its not yet implemented rather hardcoded
  _partial_: true

lossfunction:
  _target_: "torch.nn.CrossEntropyLoss"

model:
  _target_: "model.VGG"
  num_bands: 13
  num_classes: 10   

optimizer:
  _target_: "torch.optim.Adam"
  lr: 1e-4
  weight_decay: 0.05
  betas: [0.9, 0.95]

scheduler: 
  warmup_epoch: 3

dataset: 
  _target_: "dataset.EuroSat_AllBands"
  topdir_dataset: "/home/user/data/EuroSATallBands_RESTRICTED/ds/images/remote_sensing/otherDatasets/sentinel_2/tif/"
  validation_ratio: 0.3 # 0.3 is 30% sampels used for validation

dataloader:
  _target_: "torch.utils.data.DataLoader"
  shuffle: True
  batch_size: 64
  num_workers: 16
  drop_last: True

